# 1. Create a Discord bot on the Discord Developer Portal: https://discord.com/developers/applications
# 2. Get the token from the "Bot" tab
# 3. Insert the token below
# 4. Run the "/dvreload" command or reload the server
# 5. Give your players access to send a command to the bot (e.g., invite it to your Discord server)
token: "DISCORD_BOT_TOKEN"

messages:
  "not-enough-permissions": "&cNot enough permissions!"
  "invalid-link-format": "&cInvalid format! Please use: /link <player> <discordId>"
  "invalid-unlink-format": "&cInvalid format! Please use: /unlink <player>"
  "invalid-user-id-format": "&cInvalid Discord ID format!"
  "successfully-linked": "&aSuccessfully linked!"
  "successfully-unlinked": "&aSuccessfully unlinked!"
  "player-already-linked": "&cThis player is already linked!"
  "player-was-not-linked": "&cThis player was never linked!"
  "account-not-linked": "&cYour account is not linked to a Discord profile yet."
  "bot-not-working": "&cThe Discord bot is not currently working!\nAsk the administrator to resolve this issue."
  "confirm-with-command": "&6Confirm your IP via our Discord bot\nUsage: &f&n/confirm %s"
  "wait-until-verification": "&cPlease wait until you can request a new code!\n&f&n%s seconds left."
  "error-occurred": "An error occurred!"
  "its-not-your-account": "The account you're trying to confirm is not linked to your Discord profile!"
  "allowed": "Allowed!"
  "allowed-to-join-from-ip": "Successfully allowed to join from `%s`!"
  "confirm-command": "Command to verify you on the Minecraft server"
  "verification-code-you-got": "Verification code you've received from the server"
  "invalid-code": "Invalid Code!"
  "invalid-code-description": "This verification code is not valid!"
  "invalid-usage": "Invalid usage!"
  "provide-code-please": "Please provide the verification code!"
  "user-not-found": "User not found!"
  "user-not-found-description": "It seems like your account hasn't been linked to any Minecraft username yet."
  "reloaded": "&#14C60D[DiscordVerificator] Reloaded!"
  # /mc command messages
  "minecraft-command": "Command to execute (you must be online on the server)"
  "minecraft-command-argument": "Minecraft command"
  "provide-minecraft-command": "You didn't input any command to execute!"
  "multiple-players-online": "You have online players that are linked to your discord account, which one do you prefer?"
  "you-are-not-online": "You're not online on the server!"
  "minecraft-command-success": "Success!"
  "minecraft-command-executed": "Command successfully executed, now look at your chat."
  "minecraft-command-failed": "Failed!"
  "minecraft-command-fail-to-execute": "Failed to execute the command, did you disconnect?"
